### ISSUE TITLE
Have to restart when adding new filters.

### ISSUE THREAD

**Issue by Janjuks** [jakemmarsh/angularjs-gulp-browserify-boilerplate#208] opened 2016-07-27 13:29 UTC
Whenever I add new filters, I have to close currently working gulp console and do `npm run dev` again. Watcher doesn't detect any changes in newly created file and if I refresh page manually I'll always get `Unknown provider` error.

**Comment by jakemmarsh** [comment] 2016-07-29 02:17
Duplicate of #41

**Closed by jakemmarsh** 2016-07-29 02:17 UTC
