### ISSUE TITLE
UglifyJs problem?!

### ISSUE THREAD

**Issue by mnemanja** [jakemmarsh/angularjs-gulp-browserify-boilerplate#104] opened 2015-11-04 12:39 UTC
Is it possible that we can't perform the production task, because we are using the UglifyJs and they don't support ES6 yet?

Currently my production fails, and I have trouble debugging it, but the only thing that have changed is that I've updated the boilerplate.

I get this in the console as a report:

    Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
    Error: [$injector:unpr] Unknown provider: e

**Comment by jakemmarsh** [comment] 2015-11-04 18:33
It shouldn't matter whether or not Uglify supports ES6 because the Babelify transform happens before Uglify is called. The production task should now work on a fresh install, and I'm unable to replicate this error

**Comment by igorprado** [comment] 2015-11-07 15:58
I'm getting the same error here. First I thought that I may have changed something, but just did a fresh clone of the repo, and `gulp prod`. Same error.

The problem is: the `on_run` and `on_config` are getting the function params mangled by uglify. `$stateProvider` turns into `e`, and so on.. I'm looking for a fix here.

**Comment by jakemmarsh** [comment] 2015-11-07 19:47
Ahh good call. Fixed in #105

**Comment by jakemmarsh** [comment] 2015-11-07 21:25
Good call! Fixed in #105

**Closed by jakemmarsh** 2015-11-07 21:25 UTC

**Comment by igorprado** [comment] 2015-11-08 03:12
Thanks for the fast response, @jakemmarsh, but setting `mangle: false` will increase (a lot) the build file. Disabling `mangle` fix this because `ng-annotate` that is not working.

To keep the production file smaller (not disabling mangle on uglify), the solution that I found (but not a good one in my opinion), was explicitly tell to ng-annotate to annotate the files. So, on each angular file I added a directive prologue as described [here](https://github.com/olov/ng-annotate#explicit-annotations-with-nginject):

```js
function OnConfig($stateProvider, ...) {
   'ngInject';
   
   $stateProvider...
}
```

One reason that I think ng-annotate is not automatically detecting the files that need to be annotated is because you are using `bulk_require` (and `bulkify`).

**Comment by mnemanja** [comment] 2015-11-08 07:54
I solved this issue by locating the missing `ng-annotate` in my project (missing `@ngInject`). I also tried with `mangle: false` which solves the UglifyJs minification problem, when there are no dependencies defined, whether via ['dep1', 'dep2'] annotation, or via `@ngInject`.

The approach I've used to detect those cases is defining ng-strict-di, which then tells me which dependency is missing. I'm using it in all of the environments, but it's especially helpful in development, where your code is not yet mangled so that the report is meaningful.

I've had a few places of missing `@ngInject`, and fixing this fixed the problem.

Hope this helps

**Comment by jakemmarsh** [comment] 2015-11-19 00:08
@igorprado @mnemanja you guys are right, this wasn't an issue with mangling but with dependency injection. I had previously removed the explicit `ngInject` annotations as I thought it could be taken care of implicitly, but apparently not. Fix put out in PR #112, let me know what you think

**Comment by igorprado** [comment] 2015-11-19 01:40
Thanks @jakemmarsh. This was the only way that I found to solve this issue. The only problem with this approach is make sure to add this directive. Maybe a generator could solve this problem too.

**Comment by mnemanja** [comment] 2015-11-19 08:14
Thanks for addressing this @jakemmarsh. Quick question though, shouldn't adding an explicit `ngInject` be hindering the gulp task performance? There are usually a lot of places where it's not necessary to have the DI definition.

By the way could you tell me what's the difference between these two approaches:
    function ExampleCtrl() {
        'ngInject';
        ...
    }

and
     /**
    * @ngInject
    */
    function ExampleCtrl() {
        ...
    }

**Comment by jakemmarsh** [comment] 2015-11-19 19:29
@mnemanja you are correct in that it will likely affect task performance, but not by any noticeable margin. But yes, you should only be explicitly adding `ngInject` in places that require DI. I've removed it from any example files that don't need dependencies injected.

As for the prologue vs. comment approaches, there is no real difference beyond syntax/preference.

**Comment by jakemmarsh** [comment] 2015-11-19 19:55
PR #112 merged
