### ISSUE TITLE
Add babelify support for karma?

### ISSUE THREAD

**Issue by CrankNPlank** [jakemmarsh/angularjs-gulp-browserify-boilerplate#27] opened 2015-03-23 23:50 UTC
Adding babelify support for es6 is great! I'm running into issues with my unit tests, though, and I'm nearly positive it's due to not including the babelify transform with karma. I'm muddling through it, but thought I'd throw this out to you to see if you'd revisit babelify's implementation so it's handled with karma?

EDIT: Specifically, I'm able to get my tests to run by including babelify as a transform, however coverage dies with the error `[TypeError: Cannot set property 'covered' of undefined]`.

**Comment by jakemmarsh** [comment] 2015-03-24 01:23
Good catch. Should be fixed in cbe3e0fb8bfb2d8d25fb007b8b3f667e093911b1

**Comment by CrankNPlank** [comment] 2015-03-24 12:02
@jakemmarsh Thanks for the quick turnaround. After adding the preprocessor (per your commit), I'm getting `ERROR [framework.browserify]: Error: Line 9: Unexpected reserved word while parsing file: <path-to-file>` against 4 files, all of which use `class`, e.g.:

```javascript
// app/components/foo/foo.controller.js
class FooController {

  /** @ngInject */
  constructor () {

    /** Set-up the view model */
    let vm = this;

    /** A static string description for demo purposes */
    vm.description = 'Please answer the question below and be at peace.';

  }

}

module.exports = FooController;
```
In the actual file there are ngDocs preceding the class definition, so the `class` keyword is on line 9.

If I add `babelify` in karma.conf as a browserify transformation my tests pass but I get the karma-coverage error mentioned in my original post:

```javascript
// karma.conf
...
    browserify: {
      debug: true,
      transform: [
        'babelify',
        'browserify-shim',
        istanbul({
          ignore: ['**/node_modules/**', '**/test/**']
        })
      ]
    },
...
```

```console
$ gulp test:unit
[05:30:11] Using gulpfile ~/myApp/gulpfile.js
[05:30:11] Starting 'test:unit'...
[05:30:11] Starting Karma server...
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/__karma__/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X)]: Connected on socket MDaJu8uy6L7-p2K7jBL2 with id 60992949
INFO [framework.browserify]: 3483591 bytes written (4.30 seconds)
INFO [framework.browserify]: bundle built
PhantomJS 1.9.8 (Mac OS X) LOG: 'WARNING: Tried to load angular more than once.'

LOG: 'jasmine-version:1.3.1 revision 1354556913'
PhantomJS 1.9.8 (Mac OS X): Executed 37 of 37 SUCCESS (0.006 secs / 0.169 secs)
ERROR [coverage]: [TypeError: Cannot set property 'covered' of undefined]
TypeError: Cannot set property 'covered' of undefined
...
[05:30:18] Finished 'test:unit' after 7.52 s
```

The coverage docs are generated, however drilling down into them any deeper than the main `index.html` file returns a page with no styling and unresolvable links.

**Comment by jakemmarsh** [comment] 2015-03-24 15:56
That first error may be due to running the `browserify` preprocessor **before** the `babel` preprocessor. Can you try updating your `karma.conf.js` to these:

```javascript
preprocessors: {
      'app/js/**/*.js': ['babel', 'browserify', 'coverage']
    },
```

and

```javascript
plugins: [
      'karma-jasmine',
      'karma-babel-preprocessor',
      'karma-browserify',
      'karma-coverage',
      'karma-chrome-launcher',
      'karma-firefox-launcher'
    ],
```

and then try running your tests again?

**Comment by DrewML** [comment] 2015-03-24 16:01
@jakemmarsh Hopefully this isn't too off topic. Having said that, we may want to prevent having to update the `plugins` array in the future by simply removing the key in the `karma.conf` file. Per the documentation for Karma [here](http://karma-runner.github.io/0.10/config/plugins.html):

>  By default, Karma loads all NPM modules that are siblinks to it and their name matches karma-*.

**Comment by CrankNPlank** [comment] 2015-03-24 17:01
@jakemmarsh Yes, I tried that and had the same results. The only way I got past the 1st error was by adding `babelify` to the `browserify` transform. I've removed the dependency on `karma-babel-preprocessor` entirely and the transform seems to be doing the trick. All iterations produced the coverage error, though.

**Comment by DrewML** [comment] 2015-03-24 17:07
@CrankNPlank Long shot, but do you happen to have any blank files that you're running through Karma/Istanbul? Most recent report of that issue on the Karma-Runner repo identifies that as a possible culprit. https://github.com/karma-runner/karma-coverage/issues/122

**Comment by CrankNPlank** [comment] 2015-03-24 17:25
@DrewML I thought that, too, and coincidentally did have one, but removed it and still am seeing the issue. I'm still digging-in, and one clue I've found is that the coverage report seems to have generated fully for part of the application. I'm now trying to see if it died on one of the new ES6 class definitions (which is my hypothesis). I'm also tinkering with using the `isparta` instrumenter (https://github.com/douglasduteil/isparta) but still no joy.

**Comment by DrewML** [comment] 2015-03-24 17:48
Cool. If you are able to identify the minimum setup needed to reproduce the issue, I'd be happy to join you in the troubleshooting efforts. I plan to be starting up a new project shortly using ES6 with this boilerplate, so I'm invested in finding a solution.

**Comment by DrewML** [comment] 2015-03-24 17:55
From what I gather from this issue thread, it doesn't look like the current stable version of Istanbul supports ES6 - https://github.com/gotwarlost/istanbul/issues/329. One commenter does mention that Isprarta (as you mentioned) was the solution for them.

@jakemmarsh Looking over Isparta, it appears that it requires using a forked version of `karma-coverage`. Is that something you'd be comfortable with making it's way up to the mainline branch of this project?

**Comment by jakemmarsh** [comment] 2015-03-24 23:47
@DrewML cool, didn't know that about the Karma plugins. Can definitely remove it from the conf file.

@CrankNPlank it looks like you can use isparta **along with** Istanbul, so we could keep our current approach of using it as a transform ([example here](https://github.com/douglasduteil/isparta/issues/19)). Have you tried it this way?

@DrewML he mentions that the forked version is "for now". I don't think I'd be opposed to using adding isparta if it fixes the problem. Thinking the approach I linked right up above might be our best bet?

**Comment by DrewML** [comment] 2015-03-25 02:52
@jakemmarsh & @CrankNPlank: Great finds! I just implemented isparta as the instrumenter used with Istanbul (as suggested by @jakemmarsh), and it worked like a charm on the example controller provided by @CrankNPlank.

Here is an example of the coverage when the controller is `require`'d in through the `_index.js` file, but *not* injected into any Angular components:

![example screenshot](http://i.imgur.com/CMBoUS2.png).

I'll be submitting a PR momentarily.

**Comment by CrankNPlank** [comment] 2015-03-25 20:32
@DrewML & @jakemmarsh Sorry to have disappeared for a bit. I've continued debugging the `covered` issue and here are the updates.

The coverage error is being thrown if you have any additional methods in your class. Classes that only contain a constructor are getting documented without issue. For example:
```javascript
// This will work
class FooController {

  /** @ngInject */
  constructor () {

    /** Set-up the view model */
    let vm = this;

    /** A static string description for demo purposes */
    vm.description = 'Please answer the question below and be at peace.';

  }

}

// This will not (note the additional method)
class FooController {

  /** @ngInject */
  constructor () {

    /** Set-up the view model */
    let vm = this;

    /** A static string description for demo purposes */
    vm.description = 'Please answer the question below and be at peace.';

  }

  testMethod () {
    return 'Hello, World!';
  }

}
```

@DrewML would you please add a method to your test class and see if you also get the `covered` error?

**Comment by philglen** [comment] 2015-03-25 22:15
Hey Geoffrey,

How would you populate the vm with JSON data from an API, or for prototype
purposes a local JOSN file in a Œdata; directory¹?

You¹re framework is awesome but I have tried everything today to get the
View Model to accept external data, but no matter what I try the angular
does not get processed I just get {{ foo }}  outputted.

Any input would be greatly appreciated guys,

Phil Glen

From:  "Geoffrey C." <notifications@github.com>
Reply-To:  jakemmarsh/angularjs-gulp-browserify-boilerplate
<reply+00111daed69c68ace78442c89ea1fd6a34f259f3696de69892cf00000001112add729
2a169ce03ce6c6d@reply.github.com>
Date:  Wednesday, 25 March 2015 20:32
To:  jakemmarsh/angularjs-gulp-browserify-boilerplate
<angularjs-gulp-browserify-boilerplate@noreply.github.com>
Subject:  Re: [angularjs-gulp-browserify-boilerplate] Add babelify support
for karma? (#27)


@DrewML <https://github.com/DrewML>  & @jakemmarsh
<https://github.com/jakemmarsh>  Sorry to have disappeared for a bit. I've
continued debugging the covered issue and here are the updates.

The coverage error is being thrown if you have any additional methods in
your class. Classes that only contain a constructor are getting documented
without issue. For example:

// This will workclass FooController {

  /** @ngInject */
  constructor () {

    /** Set-up the view model */
    let vm = this;

    /** A static string description for demo purposes */
    vm.description = 'Please answer the question below and be at peace.';

  }

}

// This will not (note the additional method)class FooController {

  /** @ngInject */
  constructor () {

    /** Set-up the view model */
    let vm = this;

    /** A static string description for demo purposes */
    vm.description = 'Please answer the question below and be at peace.';

  }

  testMethod () {
    return 'Hello, World!';
  }

}
@DrewML <https://github.com/DrewML>  would you please add a method to your
test class and see if you also get the covered error?

‹
Reply to this email directly or view it on GitHub
<https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/issues/
27#issuecomment-86204259> .

**Comment by DrewML** [comment] 2015-03-26 16:03
@CrankNPlank No problem. I'm AFK for part of the day today, but I'll test that out as soon as I'm back at my computer.

**Comment by DrewML** [comment] 2015-03-27 01:21
@CrankNPlank Damn -- unfortunately, I'm able to replicate the same behavior. Isn't that a bummer?

I'm reading and re-reading through gotwarlost/istanbul#94 now, trying to see if our issue is related.

**Comment by DrewML** [comment] 2015-03-27 01:40
@CrankNPlank Nevermind -- got it working!

![](http://i.imgur.com/XnfDQp7.png)

Turns out that we need to use the `karma-babel-preprocessor` *instead* of using the `babelify` transform when running tests. Submitting a fix in #29 momentarily.

**Comment by CrankNPlank** [comment] 2015-03-27 03:29
@DrewML Sweet! I was tied-up in meetings all day, but I'll give this a crack tomorrow to help confirm.

**Comment by jakemmarsh** [comment] 2015-03-28 05:54
Should now be fixed in ad41083bf4954317651e8eed8d2908ca387b4e90, thanks @DrewML!

**Closed by jakemmarsh** 2015-03-28 05:54 UTC

**Comment by CrankNPlank** [comment] 2015-03-28 12:57
@DrewML & @jakemmarsh I've implemented the PR and tested and it's looking great! Thanks! The only issue I'm seeing (not a blocker) is a `WARN` when running the tests:

```bash
[06:53:12] Starting Karma server...
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/__karma__/
INFO [launcher]: Starting browser PhantomJS
WARN [preprocess]: Can not load "babel", it is not registered!
  Perhaps you are missing some plugin?
INFO [PhantomJS 1.9.8 (Mac OS X)]: Connected on socket _GBUuXedugvTO4eNcYDO with id 93725890
INFO [framework.browserify]: 4663075 bytes written (4.40 seconds)
INFO [framework.browserify]: bundle built
```
Just wanted to see if you're getting the same.

**Comment by DrewML** [comment] 2015-03-28 16:09
@CrankNPlank I can only replicate that behavior if I nuke the `karma-babel-preprocessor` directory in `node_modules`. Did you run an `npm install` after making the updates?

**Comment by CrankNPlank** [comment] 2015-03-28 18:34
@DrewML With your tip, found it. I'd been messing with my plugins, intending to remove them entirely from `karma.conf.js`, and hadn't yet. Thanks! This all looks great!!!

**Comment by DrewML** [comment] 2015-03-28 22:05
Right on! Great catch.

**Comment by ezequiel** [comment] 2015-06-25 00:36
@DrewML, in your screenshot, the numbers for Statements/Branches/Functions/Lines seem off. Is this correct?
![image](https://cloud.githubusercontent.com/assets/368069/8344509/7ade8b0a-1a97-11e5-95c3-747d921bdd4c.png)

cc @CrankNPlank @jakemmarsh
