### ISSUE TITLE
How can dist be working without @ngInject?

### ISSUE THREAD

**Issue by hakib** [jakemmarsh/angularjs-gulp-browserify-boilerplate#111] opened 2015-11-14 16:07 UTC
I tried to copy some of the patterns suggested in this repo to make a browserify-gulp-angular project work without the es6 features. It worked fine up until the point I had to uglify. It took me a while to figure out the reason nothing is annotated is because i'm missing `@ngInject` comments (thanks to [this](https://github.com/toddmotto/angularjs-styleguide#minification-and-annotation) and issue #104).

Looking at the controllers / factories / directives I noticed that most of them have no dependencies (so nothing to annotate) besides ExampleService.

So I was just wondering, is there some other voodoo here that makes annotation work without the comments? How does `OnConfig` work?

Thanks, Haki.

**Comment by jakemmarsh** [comment] 2015-11-19 00:09
@hakib I had previously removed the explicit `ngInject` annotations as I thought it could be taken care of implicitly, but apparently not. Fix put out in PR #112, let me know what you think

**Comment by hakib** [comment] 2015-11-19 06:18
LGTM. 

Couple of things though:
- Not sure why you droped the mangel option from uglify and why it's related to annotate. I found that using mangle reduced file size significantly.
- I would recommend adding [ng-strict-di](https://github.com/olov/ng-annotate#highly-recommended-enable-ng-strict-di-in-your-minified-builds). I helps with detecting injection errors during development (though i'm not sure how to add it when manually bootstrapping the app).

Thanks for sharing this project.

**Comment by jakemmarsh** [comment] 2015-11-19 19:26
1. I removed `mangle: false`, which was actually **disabling** mangle. Mangle definitely reduces file size, I had previously disabled it as I thought it was causing problems that were really caused by the ng-inject issue.
2. Added.

**Comment by hakib** [comment] 2015-11-19 19:37
Thanks man, looks great.

**Comment by jakemmarsh** [comment] 2015-11-19 19:55
Merged. Fixed in #112

**Closed by jakemmarsh** 2015-11-19 19:55 UTC
